run:
  timeout: 5m
  deadline: 1m
  tests: true
  skip-dirs:
  - .git
  - deploy
  - config
  - hack
  skip-dirs-use-default: true
  modules-download-mode: readonly
  allow-parallel-runners: true
linters-settings:
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - ifElseChain
      - octalLiteral
      - wrapperFunc
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/danmx/sigil
  gomnd:
    settings:
      mnd:
        checks:
          - argument
          - case
          - condition
          - return
          - operation
          - assign
  govet:
    check-shadowing: true
  maligned:
    suggest-new: true

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
issues:
  # Exclude scope checks in tests: "Using the variable on range scope `test` in function literal"
  exclude:
    - Using the variable on range scope `test` in function literal
