default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
        files: '.md'
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-yaml
        args:
          - --allow-multiple-documents
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.39.0
    hooks:
      - id: golangci-lint
        args:
        - --timeout
        - 2m
  - repo: local
    hooks:
      - id: fmt
        name: Run go fmt
        entry: make fmt
        language: system
        require_serial: true
        files: '.*\.go$'
        stages:
          - push
      - id: test
        name: Run tests
        entry: make test
        language: system
        require_serial: true
        files: '.*\.go$'
        stages:
          - push
