{{- if .Values.podDisruptionBudget.enable }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kms-issuer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: {{ include "kms-issuer.fullname" . }}-controller-manager
    {{- include "kms-issuer.labels" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      control-plane: {{ include "kms-issuer.fullname" . }}-controller-manager
{{- end }}
