---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kms-issuer.fullname" . }}-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - cert-manager.io
  resources:
  - certificaterequests
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificaterequests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cert-manager.skyscanner.net
  resources:
  - kmsissuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert-manager.skyscanner.net
  resources:
  - kmsissuers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cert-manager.skyscanner.net
  resources:
  - kmskeys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert-manager.skyscanner.net
  resources:
  - kmskeys/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kms-issuer.fullname" . }}-manager-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kms-issuer.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "kms-issuer.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- if .Values.args.leaderElect }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kms-issuer.fullname" . }}-leader-election-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kms-issuer.fullname" . }}-leader-election-role
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kms-issuer.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "kms-issuer.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- if .Values.certManagerApprovalRBAC.enable }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kms-issuer.fullname" . }}-cert-manager-controller-approve
rules:
- apiGroups:
  - cert-manager.io
  resourceNames:
  - kmsissuers.cert-manager.skyscanner.net/*
  resources:
  - signers
  verbs:
  - approve
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kms-issuer.fullname" . }}-cert-manager-controller-approve
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kms-issuer.fullname" . }}-cert-manager-controller-approve
subjects:
- kind: ServiceAccount
  name: {{ .Values.certManagerApprovalRBAC.serviceAccountName }}
  namespace: {{ .Values.certManagerApprovalRBAC.namespace }}
{{- end }}
{{- if .Values.enableMetricsRbacProxy }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kms-issuer.fullname" . }}-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kms-issuer.fullname" . }}-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kms-issuer.fullname" . }}-proxy-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kms-issuer.fullname" . }}-proxy-role
subjects:
- kind: ServiceAccount
  name: {{ include "kms-issuer.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
