---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: {{ include "kms-issuer.fullname" . }}-controller-manager
  name: {{ include "kms-issuer.fullname" . }}-metrics-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: {{ include "kms-issuer.fullname" . }}-controller-manager
