# permissions for end users to edit kmsissuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kmsissuer-editor-role
rules:
- apiGroups:
  - cert-manager.skyscanner.net
  resources:
  - kmsissuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert-manager.skyscanner.net
  resources:
  - kmsissuers/status
  verbs:
  - get
