# permissions for end users to view kmsissuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kmsissuer-viewer-role
rules:
- apiGroups:
  - cert-manager.skyscanner.net
  resources:
  - kmsissuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cert-manager.skyscanner.net
  resources:
  - kmsissuers/status
  verbs:
  - get
