resources:
- role.yaml
- role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
# Comment the following 4 lines if you want to disable
# the auth proxy (https://github.com/brancz/kube-rbac-proxy)
# which protects your /metrics endpoint.
- auth_proxy_service.yaml
- auth_proxy_role.yaml
- auth_proxy_role_binding.yaml
- auth_proxy_client_clusterrole.yaml
# Comment the following 2 lines if you don't wish for the internal cert-manager
# approver to approve all cert-manager.skyscanner.net CertificateRequests by default.
- cert_manager_controller_approver_clusterrole.yaml
- cert_manager_controller_approver_clusterrolebinding.yaml
