apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: {{ .Release.Name }}-controller-manager-metrics-service
  namespace:  {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: https
    port: {{ .Values.service.port }}
    targetPort: https
  selector:
    control-plane: controller-manager