name: CodeQL

on:
  pull_request:
  schedule:
    - cron: '20 17 * * 1'

jobs:
  codeql:
    name: codeql
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: actions/setup-go@v3
        with:
          go-version: ^1.17

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: go

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          version: latest

      - name: Build
        run: make build

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
