name: CodeQL

on:
  pull_request:
  schedule:
    - cron: '20 17 * * 1'

jobs:
  codeql:
    name: codeql
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: actions/setup-go@v3
        with:
          go-version: ^1.17

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: go

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          version: latest

      - name: Install kubebuilder
        run: |
          set -x
          version=2.3.1
          os=$(go env GOOS)
          arch=$(go env GOARCH)
          curl -Ls https://github.com/kubernetes-sigs/kubebuilder/releases/download/v${version}/kubebuilder_${version}_${os}_${arch}.tar.gz -o /tmp/kubebuilder_${version}.tar.gz
          shasum -a 256 -c kubebuilder_sha256.txt
          tar -xzf /tmp/kubebuilder_${version}.tar.gz -C /tmp/
          sudo mv /tmp/kubebuilder_${version}_${os}_${arch} /usr/local/kubebuilder
          export PATH=$PATH:/usr/local/kubebuilder/bin

      - name: Build
        run: make manager

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
